In [9]:
import pandas as pd

hours = ['8:00-8:45', '8:50-9:35', '9:40-10:45', '10:50-11:35', '11:40-12:25', '12:30-13:15', '13:20-14:05', '14:10-14:55', '15:00-15:45', '15:50-16:35', '16:40-17:25', '17:30-18:15', '18:20-19:05', '19:10-19:55']

In [10]:
group_0 = pd.read_csv('data/generated/group_0.csv')
group_0.rename(columns = {'Unnamed: 0':'Hours'}, inplace = True)
group_0['Hours'] = hours
group_0

,Hours,Day 1,Day 2,Day 3,Day 4,Day 5
0,8:00-8:45,{0: sala nr 1 | Jan Nowak | Język polski},{0: sala nr 1 | Jan Nowak | Język polski},{0: sala nr 1 | Mateusz Kowalski | Język niemi...,{0: sala nr 1 | Lena Kowalska | Język angielski},{0: sala nr 1 | Zofia Wiśniewska | Wychowanie ...
1,8:50-9:35,{0: sala nr 4 | Katarzyna Mazur | Fizyka},{0: sala nr 2 | Zofia Wiśniewska | Wychowanie ...,{0: sala nr 1 | Zofia Wiśniewska | Wychowanie ...,{0: sala nr 1 | Jan Nowak | Język polski},{0: sala nr 3 | Piotr Wójcik | Biologia}
2,9:40-10:45,{0: sala nr 5 | Dominik Kaczor | Informatyka},{0: sala nr 3 | Jan Nowak | Język polski},{0: sala nr 2 | Piotr Wójcik | Biologia},{0: sala nr 2 | Paweł Lewandowski | Matematyka},{0: sala nr 4 | Dominik Kaczor | Informatyka}
3,10:50-11:35,{0: sala nr 3 | Lena Kowalska | Język angielski},{0: sala nr 2 | Paweł Lewandowski | Matematyka},{0: sala nr 1 | Lena Kowalska | Język angielski},{0: sala nr 2 | Mateusz Kowalski | Język niemi...,{0: sala nr 3 | Dominik Kaczor | Informatyka}
4,11:40-12:25,{0: sala nr 2 | Lena Kowalska | Język angielski},{0: sala nr 3 | Karolina Kamińska | Chemia},{0: sala nr 5 | Karolina Kamińska | Chemia},{0: sala nr 4 | Natalia Szymańska | Geografia},{0: sala nr 2 | Paweł Lewandowski | Matematyka}
5,12:30-13:15,{0: sala nr 3 | Dominik Kaczor | Informatyka},{0: sala nr 3 | Katarzyna Mazur | Fizyka},{0: sala nr 3 | Natalia Szymańska | Geografia},{0: sala nr 2 | Dominik Kaczor | Informatyka},{0: sala nr 1 | Katarzyna Mazur | Fizyka}
6,13:20-14:05,{},{0: sala nr 2 | Paweł Lewandowski | Matematyka},{},{},{0: sala nr 1 | Paweł Lewandowski | Matematyka}
7,14:10-14:55,{},{},{},{},{}
8,15:00-15:45,{},{},{},{},{}
9,15:50-16:35,{},{},{},{},{}
10,16:40-17:25,{},{},{},{},{}
11,17:30-18:15,{},{},{},{},{0: sala nr 10 | Katarzyna Mazur | Fizyka}
12,18:20-19:05,{},{},{},{},{}
13,19:10-19:55,{},{},{},{},{}

In [11]:
group_1 = pd.read_csv('data/generated/group_1.csv')
group_1.rename(columns = {'Unnamed: 0':'Hours'}, inplace = True)
group_1['Hours'] = hours
group_1

,Hours,Day 1,Day 2,Day 3,Day 4,Day 5
0,8:00-8:45,{0: sala nr 3 | Zofia Wiśniewska | Wychowanie ...,{0: sala nr 2 | Lena Kowalska | Język angielski},{0: sala nr 5 | Piotr Wójcik | Biologia},{0: sala nr 5 | Zofia Wiśniewska | Wychowanie ...,{0: sala nr 5 | Jan Nowak | Język polski}
1,8:50-9:35,{0: sala nr 2 | Mateusz Kowalski | Język niemi...,{0: sala nr 4 | Jan Nowak | Język polski},{0: sala nr 2 | Karolina Kamińska | Chemia},{0: sala nr 2 | Lena Kowalska | Język angielski},{0: sala nr 4 | Mateusz Kowalski | Język niemi...
2,9:40-10:45,{0: sala nr 3 | Katarzyna Mazur | Fizyka},{0: sala nr 1 | Piotr Wójcik | Biologia},{0: sala nr 3 | Lena Kowalska | Język angielski},{0: sala nr 4 | Zofia Wiśniewska | Wychowanie ...,{0: sala nr 2 | Jan Nowak | Język polski}
3,10:50-11:35,{0: sala nr 4 | Paweł Lewandowski | Matematyka},{0: sala nr 1 | Lena Kowalska | Język angielski},{0: sala nr 4 | Dominik Kaczor | Informatyka},{0: sala nr 1 | Katarzyna Mazur | Fizyka},{0: sala nr 1 | Paweł Lewandowski | Matematyka}
4,11:40-12:25,{0: sala nr 3 | Natalia Szymańska | Geografia},{0: sala nr 1 | Paweł Lewandowski | Matematyka},{0: sala nr 1 | Dominik Kaczor | Informatyka},{0: sala nr 2 | Karolina Kamińska | Chemia},{0: sala nr 4 | Dominik Kaczor | Informatyka}
5,12:30-13:15,{0: sala nr 1 | Katarzyna Mazur | Fizyka},{},{},{0: sala nr 4 | Natalia Szymańska | Geografia},{}
6,13:20-14:05,{0: sala nr 2 | Dominik Kaczor | Informatyka},{0: sala nr 3 | Katarzyna Mazur | Fizyka},{},{},{}
7,14:10-14:55,{0: sala nr 2 | Paweł Lewandowski | Matematyka},{0: sala nr 1 | Dominik Kaczor | Informatyka},{},{},{}
8,15:00-15:45,{},{0: sala nr 1 | Jan Nowak | Język polski},{},{},{}
9,15:50-16:35,{},{0: sala nr 1 | Paweł Lewandowski | Matematyka},{},{},{}
10,16:40-17:25,{},{},{},{},{}
11,17:30-18:15,{},{},{},{},{}
12,18:20-19:05,{},{},{},{},{}
13,19:10-19:55,{},{},{},{},{}

In [12]:
group_2 = pd.read_csv('data/generated/group_2.csv')
group_2.rename(columns = {'Unnamed: 0':'Hours'}, inplace = True)
group_2['Hours'] = hours
group_2

,Hours,Day 1,Day 2,Day 3,Day 4,Day 5
0,8:00-8:45,{0: sala nr 5 | Piotr Wójcik | Biologia},{0: sala nr 4 | Dominik Kaczor | Informatyka},{0: sala nr 4 | Lena Kowalska | Język angielski},{0: sala nr 3 | Piotr Wójcik | Biologia},{0: sala nr 4 | Mateusz Kowalski | Język niemi...
1,8:50-9:35,{0: sala nr 5 | Jan Nowak | Język polski},{0: sala nr 5 | Lena Kowalska | Język angielski},{0: sala nr 4 | Paweł Lewandowski | Matematyka},{0: sala nr 4 | Dominik Kaczor | Informatyka},{0: sala nr 5 | Jan Nowak | Język polski}
2,9:40-10:45,{0: sala nr 1 | Lena Kowalska | Język angielski},{0: sala nr 5 | Paweł Lewandowski | Matematyka},{0: sala nr 1 | Mateusz Kowalski | Język niemi...,{0: sala nr 3 | Lena Kowalska | Język angielski},{0: sala nr 5 | Zofia Wiśniewska | Wychowanie ...
3,10:50-11:35,{0: sala nr 1 | Katarzyna Mazur | Fizyka},{0: sala nr 4 | Dominik Kaczor | Informatyka},{0: sala nr 2 | Jan Nowak | Język polski},{0: sala nr 4 | Jan Nowak | Język polski},{0: sala nr 2 | Natalia Szymańska | Geografia}
4,11:40-12:25,{0: sala nr 5 | Zofia Wiśniewska | Wychowanie ...,{0: sala nr 4 | Zofia Wiśniewska | Wychowanie ...,{0: sala nr 4 | Katarzyna Mazur | Fizyka},{0: sala nr 1 | Paweł Lewandowski | Matematyka},{0: sala nr 1 | Natalia Szymańska | Geografia}
5,12:30-13:15,{0: sala nr 5 | Karolina Kamińska | Chemia},{0: sala nr 4 | Dominik Kaczor | Informatyka},{0: sala nr 1 | Paweł Lewandowski | Matematyka},{0: sala nr 1 | Katarzyna Mazur | Fizyka},{0: sala nr 2 | Dominik Kaczor | Informatyka}
6,13:20-14:05,{0: sala nr 1 | Katarzyna Mazur | Fizyka},{},{0: sala nr 1 | Paweł Lewandowski | Matematyka},{},{}
7,14:10-14:55,{},{},{},{},{}
8,15:00-15:45,{},{},{},{},{}
9,15:50-16:35,{},{},{},{},{}
10,16:40-17:25,{},{},{},{},{}
11,17:30-18:15,{},{},{},{},{}
12,18:20-19:05,{},{},{0: sala nr 1 | Karolina Kamińska | Chemia},{},{}
13,19:10-19:55,{},{},{},{},{}

In [13]:
group_3 = pd.read_csv('data/generated/group_3.csv')
group_3.rename(columns = {'Unnamed: 0':'Hours'}, inplace = True)
group_3['Hours'] = hours
group_3

,Hours,Day 1,Day 2,Day 3,Day 4,Day 5
0,8:00-8:45,{0: sala nr 2 | Lena Kowalska | Język angielski},{0: sala nr 3 | Katarzyna Mazur | Fizyka},{0: sala nr 3 | Jan Nowak | Język polski},{0: sala nr 4 | Jan Nowak | Język polski},{0: sala nr 3 | Lena Kowalska | Język angielski}
1,8:50-9:35,{0: sala nr 1 | Zofia Wiśniewska | Wychowanie ...,{0: sala nr 3 | Mateusz Kowalski | Język niemi...,{0: sala nr 5 | Piotr Wójcik | Biologia},{0: sala nr 5 | Katarzyna Mazur | Fizyka},{0: sala nr 1 | Zofia Wiśniewska | Wychowanie ...
2,9:40-10:45,{0: sala nr 4 | Mateusz Kowalski | Język niemi...,{0: sala nr 4 | Natalia Szymańska | Geografia},{0: sala nr 5 | Katarzyna Mazur | Fizyka},{0: sala nr 5 | Jan Nowak | Język polski},{0: sala nr 3 | Piotr Wójcik | Biologia}
3,10:50-11:35,{0: sala nr 5 | Zofia Wiśniewska | Wychowanie ...,{0: sala nr 5 | Jan Nowak | Język polski},{0: sala nr 3 | Karolina Kamińska | Chemia},{0: sala nr 3 | Lena Kowalska | Język angielski},{0: sala nr 5 | Lena Kowalska | Język angielski}
4,11:40-12:25,{0: sala nr 1 | Dominik Kaczor | Informatyka},{0: sala nr 5 | Dominik Kaczor | Informatyka},{0: sala nr 3 | Paweł Lewandowski | Matematyka},{0: sala nr 5 | Dominik Kaczor | Informatyka},{0: sala nr 5 | Karolina Kamińska | Chemia}
5,12:30-13:15,{0: sala nr 4 | Paweł Lewandowski | Matematyka},{0: sala nr 2 | Natalia Szymańska | Geografia},{0: sala nr 2 | Katarzyna Mazur | Fizyka},{},{0: sala nr 3 | Paweł Lewandowski | Matematyka}
6,13:20-14:05,{0: sala nr 3 | Paweł Lewandowski | Matematyka},{},{0: sala nr 2 | Dominik Kaczor | Informatyka},{0: sala nr 2 | Dominik Kaczor | Informatyka},{}
7,14:10-14:55,{},{},{},{},{}
8,15:00-15:45,{},{},{},{},{}
9,15:50-16:35,{},{},{},{},{}
10,16:40-17:25,{},{},{},{},{}
11,17:30-18:15,{},{},{0: sala nr 1 | Paweł Lewandowski | Matematyka},{},{}
12,18:20-19:05,{},{},{},{},{}
13,19:10-19:55,{},{},{},{},{}

In [14]:
group_4 = pd.read_csv('data/generated/group_4.csv')
group_4.rename(columns = {'Unnamed: 0':'Hours'}, inplace = True)
group_4['Hours'] = hours
group_4

,Hours,Day 1,Day 2,Day 3,Day 4,Day 5
0,8:00-8:45,{0: sala nr 4 | Mateusz Kowalski | Język niemi...,{0: sala nr 5 | Paweł Lewandowski | Matematyka},{0: sala nr 2 | Zofia Wiśniewska | Wychowanie ...,{0: sala nr 2 | Mateusz Kowalski | Język niemi...,{0: sala nr 2 | Piotr Wójcik | Biologia}
1,8:50-9:35,{0: sala nr 3 | Lena Kowalska | Język angielski},{0: sala nr 1 | Dominik Kaczor | Informatyka},{0: sala nr 3 | Jan Nowak | Język polski},{0: sala nr 3 | Zofia Wiśniewska | Wychowanie ...,{0: sala nr 2 | Lena Kowalska | Język angielski}
2,9:40-10:45,{0: sala nr 2 | Jan Nowak | Język polski},{0: sala nr 2 | Lena Kowalska | Język angielski},{0: sala nr 4 | Jan Nowak | Język polski},{0: sala nr 1 | Katarzyna Mazur | Fizyka},{0: sala nr 1 | Lena Kowalska | Język angielski}
3,10:50-11:35,{0: sala nr 2 | Jan Nowak | Język polski},{0: sala nr 3 | Karolina Kamińska | Chemia},{0: sala nr 5 | Zofia Wiśniewska | Wychowanie ...,{0: sala nr 5 | Piotr Wójcik | Biologia},{0: sala nr 4 | Karolina Kamińska | Chemia}
4,11:40-12:25,{0: sala nr 4 | Paweł Lewandowski | Matematyka},{0: sala nr 2 | Katarzyna Mazur | Fizyka},{0: sala nr 2 | Natalia Szymańska | Geografia},{0: sala nr 3 | Katarzyna Mazur | Fizyka},{0: sala nr 3 | Katarzyna Mazur | Fizyka}
5,12:30-13:15,{0: sala nr 2 | Natalia Szymańska | Geografia},{0: sala nr 1 | Paweł Lewandowski | Matematyka},{0: sala nr 4 | Dominik Kaczor | Informatyka},{0: sala nr 3 | Paweł Lewandowski | Matematyka},{}
6,13:20-14:05,{},{0: sala nr 1 | Dominik Kaczor | Informatyka},{},{0: sala nr 1 | Paweł Lewandowski | Matematyka},{0: sala nr 2 | Dominik Kaczor | Informatyka}
7,14:10-14:55,{0: sala nr 1 | Dominik Kaczor | Informatyka},{},{},{},{}
8,15:00-15:45,{},{},{},{},{}
9,15:50-16:35,{},{},{},{},{}
10,16:40-17:25,{},{},{},{},{}
11,17:30-18:15,{},{},{},{},{}
12,18:20-19:05,{},{},{},{},{}
13,19:10-19:55,{},{},{},{},{}

In [15]:
group_5 = pd.read_csv('data/generated/group_5.csv')
group_5.rename(columns = {'Unnamed: 0':'Hours'}, inplace = True)
group_5['Hours'] = hours
group_5

,Hours,Day 1,Day 2,Day 3,Day 4,Day 5
0,8:00-8:45,{0: sala nr 3 | Mateusz Kowalski | Język niemi...,{0: sala nr 3 | Zofia Wiśniewska | Wychowanie ...,{0: sala nr 1 | Natalia Szymańska | Geografia},{0: sala nr 7 | Natalia Szymańska | Geografia},{0: sala nr 6 | Karolina Kamińska | Chemia}
1,8:50-9:35,{0: sala nr 5 | Piotr Wójcik | Biologia},{0: sala nr 7 | Katarzyna Mazur | Fizyka},{0: sala nr 2 | Jan Nowak | Język polski},{0: sala nr 1 | Dominik Kaczor | Informatyka},{0: sala nr 3 | Jan Nowak | Język polski}
2,9:40-10:45,{0: sala nr 5 | Mateusz Kowalski | Język niemi...,{0: sala nr 1 | Zofia Wiśniewska | Wychowanie ...,{0: sala nr 6 | Piotr Wójcik | Biologia},{0: sala nr 6 | Zofia Wiśniewska | Wychowanie ...,{0: sala nr 5 | Karolina Kamińska | Chemia}
3,10:50-11:35,{0: sala nr 5 | Jan Nowak | Język polski},{0: sala nr 3 | Paweł Lewandowski | Matematyka},{0: sala nr 3 | Dominik Kaczor | Informatyka},{0: sala nr 7 | Paweł Lewandowski | Matematyka},{0: sala nr 4 | Paweł Lewandowski | Matematyka}
4,11:40-12:25,{0: sala nr 3 | Lena Kowalska | Język angielski},{0: sala nr 7 | Dominik Kaczor | Informatyka},{0: sala nr 1 | Katarzyna Mazur | Fizyka},{0: sala nr 4 | Jan Nowak | Język polski},{0: sala nr 5 | Paweł Lewandowski | Matematyka}
5,12:30-13:15,{0: sala nr 2 | Katarzyna Mazur | Fizyka},{0: sala nr 3 | Lena Kowalska | Język angielski},{0: sala nr 2 | Lena Kowalska | Język angielski},{0: sala nr 4 | Lena Kowalska | Język angielski},{}
6,13:20-14:05,{},{0: sala nr 3 | Dominik Kaczor | Informatyka},{},{},{}
7,14:10-14:55,{},{0: sala nr 1 | Paweł Lewandowski | Matematyka},{0: sala nr 1 | Dominik Kaczor | Informatyka},{},{}
8,15:00-15:45,{},{},{},{},{}
9,15:50-16:35,{},{},{},{},{}
10,16:40-17:25,{},{},{},{},{}
11,17:30-18:15,{},{},{},{},{}
12,18:20-19:05,{},{},{},{},{}
13,19:10-19:55,{},{0: sala nr 1 | Katarzyna Mazur | Fizyka},{},{},{}

In [16]:
group_6 = pd.read_csv('data/generated/group_6.csv')
group_6.rename(columns = {'Unnamed: 0':'Hours'}, inplace = True)
group_6['Hours'] = hours
group_6

,Hours,Day 1,Day 2,Day 3,Day 4,Day 5
0,8:00-8:45,{0: sala nr 4 | Zofia Wiśniewska | Wychowanie ...,{0: sala nr 4 | Karolina Kamińska | Chemia},{0: sala nr 3 | Katarzyna Mazur | Fizyka},{0: sala nr 4 | Jan Nowak | Język polski},{0: sala nr 7 | Piotr Wójcik | Biologia}
1,8:50-9:35,{0: sala nr 4 | Katarzyna Mazur | Fizyka},{0: sala nr 4 | Jan Nowak | Język polski},{0: sala nr 6 | Lena Kowalska | Język angielski},{0: sala nr 7 | Paweł Lewandowski | Matematyka},{0: sala nr 5 | Lena Kowalska | Język angielski}
2,9:40-10:45,{0: sala nr 2 | Dominik Kaczor | Informatyka},{0: sala nr 7 | Lena Kowalska | Język angielski},{0: sala nr 7 | Mateusz Kowalski | Język niemi...,{0: sala nr 7 | Lena Kowalska | Język angielski},{0: sala nr 4 | Jan Nowak | Język polski}
3,10:50-11:35,{0: sala nr 3 | Mateusz Kowalski | Język niemi...,{0: sala nr 5 | Zofia Wiśniewska | Wychowanie ...,{0: sala nr 2 | Zofia Wiśniewska | Wychowanie ...,{0: sala nr 1 | Piotr Wójcik | Biologia},{0: sala nr 3 | Natalia Szymańska | Geografia}
4,11:40-12:25,{0: sala nr 5 | Karolina Kamińska | Chemia},{0: sala nr 5 | Katarzyna Mazur | Fizyka},{0: sala nr 7 | Paweł Lewandowski | Matematyka},{0: sala nr 7 | Paweł Lewandowski | Matematyka},{0: sala nr 1 | Natalia Szymańska | Geografia}
5,12:30-13:15,{},{},{},{},{}
6,13:20-14:05,{0: sala nr 3 | Paweł Lewandowski | Matematyka},{},{0: sala nr 1 | Katarzyna Mazur | Fizyka},{0: sala nr 2 | Paweł Lewandowski | Matematyka},{}
7,14:10-14:55,{},{},{},{0: sala nr 2 | Dominik Kaczor | Informatyka},{0: sala nr 1 | Dominik Kaczor | Informatyka}
8,15:00-15:45,{},{},{0: sala nr 1 | Dominik Kaczor | Informatyka},{},{0: sala nr 1 | Dominik Kaczor | Informatyka}
9,15:50-16:35,{},{},{},{},{}
10,16:40-17:25,{},{},{},{},{}
11,17:30-18:15,{},{},{},{},{}
12,18:20-19:05,{},{},{0: sala nr 1 | Jan Nowak | Język polski},{},{}
13,19:10-19:55,{},{},{},{},{}